### ISSUE TITLE
Reorganizing components

### ISSUE THREAD

**Issue by zenorocha** [liferay-apps/ui-kit#47]
Right now we've a bunch of components and they're visually inconsistent. Some may have CSS code snippets, others doesn't. Some may be need a JavaScript code snippet, others doesn't.

I suggest we group them into different pages, something like: `Guidelines | CSS | JavaScript`.

## Guidelines

> Should list things that doesn't contain any code.

* Color: Primary
* Color: Secondary
* Typography: Fonts
* Typography: Sizes
* Typography: Contrast

## CSS

> Should list components that only contain CSS code.

* Avatar: Photos
* Avatar: Initials
* Avatar: Icons
* Button: Types
* Button: Tags
* Form: Input
* Icons: 12x12
* Icons: 16x16
* Shadows
* Navigation: Topbar
* Navigation: Sidebar
* Navigation: Menu

## JavaScript

> Should list components that contains both CSS and JS code.

* Modal
* Modal: Dialog
* Tooltips
* Selects: Action Menu
* Selects: Color
* Selects: Switchers

**Comment by eduardolundgren** [comment]
+1

**Comment by vitorfernandes** [comment]
One of the things we discussed was, instead do this org, we'll add tags to each cell (CSS / JavaScript), and we'll put tabs as filters on the topbar. This good because we can organize the components by alphabetical order on the sidelist,  and we can keep the idea of organize the things by code. :dango: 

Tell me @eduardolundgren ?

**Comment by vitorfernandes** [comment]
Besides these things, we can have a search bar there also.
